---
- name: "Download Munki"
  include_role:
    name: "coreyramirezgomez.github_release_retriever"
  vars:
    github_release_retriever_project: "munki/munki"
    github_release_retriever_version: "{{ autopkgr_munki_install_version }}"
    github_release_retriever_filetype: ".pkg"
- name: "Download autopkg"
  include_role:
    name: "coreyramirezgomez.github_release_retriever"
  vars:
    github_release_retriever_project: "autopkg/autopkg"
    github_release_retriever_version: "{{ autopkgr_autopkg_install_version }}"
    github_release_retriever_filetype: ".pkg"
- name: "Install autopkg and munki"
  command: "{{ autopkgr_bin_installer }} -pkg {{ item.dest }} -target /"
  become: true
  register: results
  changed_when: "'installer: The install was successful.' in results.stdout or 'installer: The upgrade was successful.' in results.stdout"
  with_items: "{{ github_release_retriever_downloads.results }}"
