---
# tasks file for autopkgr
- name: "Debug"
  include_tasks:
    file: debug.yml
  when: "'debug' in autopkgr_actions"
- name: assert that os_family is supported
  assert:
    that: ansible_distribution in ['MacOSX']
- name: "Install Dependencies"
  include_tasks:
    file: install.yml
  when: "'install' in autopkgr_actions"
- name: "Configure Host"
  include_tasks:
    file: configure.yml
  when: "'configure' in autopkgr_actions"
- name: "Build Packages"
  include_tasks:
    file: build.yml
  when: "'build' in autopkgr_actions"
