---
# tasks file for autopkgr
- name: assert that os_family is supported
  assert:
    that: ansible_distribution in ['MacOSX']
- name: autopkgr/tasks/main - Install Dependencies
  include_tasks:
    file: install.yml
    apply:
      tags:
        - install
  when: "'install' in autopkgr_actions"
  tags:
    - install
- name: autopkgr/tasks/main - Configure Host
  include_tasks:
    file: configure.yml
    apply:
      tags:
        - configure
  when: "'configure' in autopkgr_actions"
  tags:
    - configure
- name: autopkgr/tasks/main - Build Packages
  include_tasks:
    file:  build.yml
    apply:
      tags:
        - build
  when: "'build' in autopkgr_actions"
  tags:
    - build
